# Include this file from postgresql.conf after the pgBackRest repository is ready.
wal_level = replica
archive_mode = on
archive_timeout = '60s'
archive_command = 'pgbackrest --stanza=edutrack archive-push %p'
max_wal_senders = 10
wal_keep_size = '2048MB'
