// @vitest-environment jsdom
import React, { useState } from 'react';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi } from 'vitest';
import type { Class, SafeStudent } from '../../../../types';
import { StudentFormModal } from './StudentFormModal';

type MockChildrenProps = { children?: React.ReactNode };
type MockMotionDivProps = React.ComponentPropsWithoutRef<'div'> & {
  initial?: unknown;
  animate?: unknown;
  exit?: unknown;
};

vi.mock('framer-motion', () => ({
  AnimatePresence: ({ children }: MockChildrenProps) => <>{children}</>,
  motion: {
    div: ({ initial: _initial, animate: _animate, exit: _exit, ...props }: MockMotionDivProps) => (
      <div {...props} />
    ),
  },
}));

vi.mock('../../../../components/common/ModalPortal', () => ({
  ModalPortal: ({ children }: MockChildrenProps) => <>{children}</>,
}));

const classes: Class[] = [
  {
    id: 'alpha',
    name: 'Alpha',
    weeklySessions: [{ dayOfWeek: 2, startTime: '17:30', endTime: '19:00' }],
    schedule: '',
    daysOfWeek: [],
    description: '',
    startDate: '2026-07-01',
    endDate: '2026-12-31',
    startTime: '',
    teacherId: 'teacher-1',
    status: 'active',
    createdAt: '2026-07-01T00:00:00.000Z',
  },
  {
    id: 'crossed',
    name: 'Crossed',
    weeklySessions: [
      { dayOfWeek: 1, startTime: '17:30', endTime: '19:00' },
      { dayOfWeek: 2, startTime: '18:30', endTime: '20:00' },
    ],
    schedule: '',
    daysOfWeek: [],
    description: '',
    startDate: '2026-07-01',
    endDate: '2026-12-31',
    startTime: '',
    teacherId: 'teacher-1',
    status: 'active',
    createdAt: '2026-07-01T00:00:00.000Z',
  },
];

const t = {
  close: 'Close',
  genderLabel: 'Gender',
  selectGender: 'Select gender',
  male: 'Male',
  female: 'Female',
  other: 'Other',
  autoGeneratedId: 'Auto generated',
  gradeOption: 'Grade {grade}',
  gradeSuggestion: 'Suggested grade {grade}',
  contactSmsHint: '',
  saving: 'Saving',
  saveChanges: 'Save changes',
  modal: {
    addTitle: 'Add student',
    editTitle: 'Edit student',
    faceLabel: 'Face',
    nameLabel: 'Name',
    namePlaceholder: 'Name',
    gradeLabel: 'Grade',
    selectGrade: 'Select grade',
    idLabel: 'ID',
    dobLabel: 'Date of birth',
    classLabel: 'Class',
    selectClass: 'Select class',
    contactLabel: 'Contact',
    contactPlaceholder: 'Contact',
    openCamera: 'Open camera',
    takePhoto: 'Take photo',
    save: 'Save',
    scheduleDayFilter: 'Filter by weekday',
    allScheduleDays: 'All weekdays',
    scheduleStartTimeFilter: 'Filter by start time',
    allStartTimes: 'All start times',
    noMatchingClasses: 'No matching classes',
    weekdayLabels: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  },
  messages: {
    cameraRetake: 'Retake',
    cameraUpload: 'Upload',
    cameraReq: '',
    studentInfoLoginDesc: '',
  },
};

const emptyForm = {
  name: '',
  studentId: '',
  dob: '',
  contact: '',
  classId: '',
  faceImage: '',
  faceImageStoragePath: '',
  code: '',
  gender: '' as 'male' | 'female' | 'other' | '',
  grade: '',
};

function Harness({
  editingStudent = null,
  initialClassId = '',
  initialGrade = '',
  isOpen = true,
  availableClasses = classes,
}: {
  editingStudent?: SafeStudent | null;
  initialClassId?: string;
  initialGrade?: string;
  isOpen?: boolean;
  availableClasses?: Class[];
}) {
  const [formData, setFormData] = useState({
    ...emptyForm,
    classId: initialClassId,
    grade: initialGrade,
  });

  return (
    <>
      <output data-testid="selected-class-id">{formData.classId}</output>
      <output data-testid="selected-grade">{formData.grade}</output>
      <StudentFormModal
        isOpen={isOpen}
        onClose={vi.fn()}
        editingStudent={editingStudent}
        formData={formData}
        setFormData={setFormData}
        classes={availableClasses}
        sortedClasses={availableClasses}
        teachers={[{ uid: 'teacher-1', displayName: 'Teacher One' }]}
        isSaving={false}
        isCameraActive={false}
        videoRef={{ current: null }}
        handleSubmit={vi.fn()}
        handleModalClose={vi.fn()}
        startCamera={vi.fn()}
        stopCamera={vi.fn()}
        capturePhoto={vi.fn()}
        handleFileUpload={vi.fn()}
        t={t}
        tc={{ cancel: 'Cancel' }}
      />
    </>
  );
}

function ReopenHarness() {
  const [isOpen, setIsOpen] = useState(true);

  return (
    <>
      <button type="button" onClick={() => setIsOpen(false)}>
        close modal
      </button>
      <button type="button" onClick={() => setIsOpen(true)}>
        open modal
      </button>
      <Harness isOpen={isOpen} />
    </>
  );
}

describe('StudentFormModal class schedule filters', () => {
  it('filters weekday and time on the same session and shows schedule labels', async () => {
    const user = userEvent.setup();
    render(<Harness />);

    const timeFilter = screen.getByRole('combobox', { name: 'Filter by start time' });
    expect(
      within(timeFilter)
        .getAllByRole('option')
        .map((option) => option.textContent)
    ).toEqual(['All start times', '17:30', '18:30']);

    await user.selectOptions(screen.getByRole('combobox', { name: 'Filter by weekday' }), '2');
    await user.selectOptions(timeFilter, '17:30');

    const classSelect = screen.getByRole('combobox', { name: 'Class' });
    expect(
      within(classSelect).getByRole('option', {
        name: /Alpha.*Tuesday 17:30 - 19:00/,
      })
    ).toBeVisible();
    expect(within(classSelect).queryByRole('option', { name: /Crossed/ })).not.toBeInTheDocument();
  });

  it('clears a selected class but keeps grade when filters exclude it', async () => {
    const user = userEvent.setup();
    render(<Harness initialClassId="crossed" initialGrade="6" />);

    await user.selectOptions(screen.getByRole('combobox', { name: 'Filter by weekday' }), '2');
    await user.selectOptions(
      screen.getByRole('combobox', { name: 'Filter by start time' }),
      '17:30'
    );

    await waitFor(() => expect(screen.getByRole('combobox', { name: 'Class' })).toHaveValue(''));
    expect(screen.getByTestId('selected-grade')).toHaveTextContent('6');
  });

  it('keeps a seeded class while no schedule filter is active and classes are loading', () => {
    render(<Harness initialClassId="seed-class" availableClasses={[]} />);

    expect(screen.getByTestId('selected-class-id')).toHaveTextContent('seed-class');
  });

  it('does not show schedule filters while editing a student', () => {
    render(<Harness editingStudent={{ id: 'student-1' } as SafeStudent} />);

    expect(screen.queryByRole('combobox', { name: 'Filter by weekday' })).not.toBeInTheDocument();
    expect(
      screen.queryByRole('combobox', { name: 'Filter by start time' })
    ).not.toBeInTheDocument();
  });

  it('shows an explicit empty result when no class matches', async () => {
    const user = userEvent.setup();
    render(<Harness />);

    await user.selectOptions(screen.getByRole('combobox', { name: 'Filter by weekday' }), '6');

    expect(
      within(screen.getByRole('combobox', { name: 'Class' })).getByRole('option', {
        name: 'No matching classes',
      })
    ).toBeVisible();
  });

  it('resets schedule filters when the create modal is reopened', async () => {
    const user = userEvent.setup();
    render(<ReopenHarness />);

    await user.selectOptions(screen.getByRole('combobox', { name: 'Filter by weekday' }), '2');
    await user.click(screen.getByRole('button', { name: 'close modal' }));
    await user.click(screen.getByRole('button', { name: 'open modal' }));

    expect(screen.getByRole('combobox', { name: 'Filter by weekday' })).toHaveValue('');
    expect(screen.getByRole('combobox', { name: 'Filter by start time' })).toHaveValue('');
  });
});
