import type {
  CenterReportExpenseDetailsResponse,
  CenterReportIncomeDetailsResponse,
  ExpenseTransactionDetail,
  IncomeTransactionDetail,
} from '../../../../lib/api/financeApi';
import type { FinanceDetailsText } from './types';

export const detailsText: FinanceDetailsText = {
  details: {
    viewDetails: 'Xem chi tiết',
    incomeTitle: 'Chi tiết khoản thu',
    expenseTitle: 'Chi tiết khoản chi',
    transactionCount: 'Số chứng từ',
    totalAmount: 'Tổng tiền',
    loading: 'Đang tải chi tiết...',
    emptyIncome: 'Không có khoản thu trong kỳ này.',
    emptyExpense: 'Không có khoản chi trong kỳ này.',
    loadError: 'Không thể tải chi tiết giao dịch.',
    retry: 'Thử lại',
    close: 'Đóng',
    previousPage: 'Trang trước',
    nextPage: 'Trang sau',
    page: 'Trang',
    notAvailable: 'Không có dữ liệu',
    heldInWallet: 'Tiền đang giữ trong ví',
    showAllocations: 'Xem phân bổ',
    hideAllocations: 'Ẩn phân bổ',
    methods: {
      cash: 'Tiền mặt',
      transfer: 'Chuyển khoản',
      other: 'Khác',
    },
    categories: {
      salary: 'Lương',
      rent: 'Tiền thuê',
      utilities: 'Điện nước',
      marketing: 'Marketing',
      supplies: 'Vật tư',
      other: 'Khác',
      wallet_refund: 'Hoàn tiền học sinh',
    },
    income: {
      receiptNo: 'Số phiếu thu',
      invoiceNo: 'Số hóa đơn',
      receivedDate: 'Ngày thu',
      student: 'Học sinh',
      phone: 'Số điện thoại',
      className: 'Lớp',
      paymentMethod: 'Phương thức',
      amountReceived: 'Tiền thực thu',
      amountDue: 'Phải thanh toán hiện tại',
      remainingAmount: 'Công nợ hiện tại',
      walletBalance: 'Số dư ví hiện tại',
      allocatedAmount: 'Đã cấn công nợ',
    },
    expense: {
      expenseNo: 'Số phiếu chi',
      paidDate: 'Ngày chi',
      category: 'Hạng mục',
      content: 'Nội dung',
      amount: 'Số tiền',
      payee: 'Người nhận',
      createdBy: 'Người lập phiếu',
      student: 'Học sinh',
    },
  },
};

export const incomeRow: IncomeTransactionDetail = {
  id: 'r1',
  receiptNo: 'PT-260730-001',
  invoiceNo: 'INV-260730-001',
  receivedDate: '2026-07-30',
  studentId: 's1',
  studentName: 'Nguyễn An',
  studentCode: 'HS001',
  phone: '0901234567',
  paymentMethod: 'transfer',
  amountReceived: 1_000_000,
  amountDue: 1_800_000,
  remainingAmount: 800_000,
  walletBalance: 250_000,
  walletDeposit: false,
  note: '',
  allocations: [
    {
      ledgerId: 'l1',
      classId: 'c1',
      className: 'IELTS 6.5',
      allocatedAmount: 1_000_000,
      amountDue: 1_800_000,
      remainingAmount: 800_000,
      dataAvailable: true,
    },
  ],
};

export const walletOnlyRow: IncomeTransactionDetail = {
  id: 'r-wallet',
  receiptNo: 'PT-260730-002',
  invoiceNo: '',
  receivedDate: '2026-07-30',
  studentId: 's1',
  studentName: 'Nguyễn An',
  studentCode: 'HS001',
  phone: '0901234567',
  paymentMethod: 'cash',
  amountReceived: 400_000,
  amountDue: 0,
  remainingAmount: 0,
  walletBalance: 400_000,
  walletDeposit: true,
  note: '',
  allocations: [],
};

export const unavailableLegacyRow: IncomeTransactionDetail = {
  id: 'r-legacy',
  receiptNo: 'PT-260730-003',
  invoiceNo: '',
  receivedDate: '2026-07-30',
  studentId: 'missing-student',
  studentName: '',
  studentCode: '',
  phone: '',
  paymentMethod: 'other',
  amountReceived: 300_000,
  amountDue: 0,
  remainingAmount: 0,
  walletBalance: 0,
  walletDeposit: false,
  note: '',
  allocations: [
    {
      ledgerId: 'missing-ledger',
      classId: 'missing-class',
      className: '',
      allocatedAmount: 300_000,
      amountDue: 0,
      remainingAmount: 0,
      dataAvailable: false,
    },
  ],
};

export const expenseRow: ExpenseTransactionDetail = {
  id: 'e1',
  expenseNo: 'PC-260730-001',
  paidDate: '2026-07-30',
  category: 'wallet_refund',
  amount: 200_000,
  purpose: '',
  reason: 'Hoàn học phí thừa',
  note: '',
  payee: 'Phụ huynh Nguyễn An',
  createdBy: 'accountant-1',
  createdByName: 'Kế toán Lan',
  type: 'wallet_refund',
  studentId: 's1',
  studentName: 'Nguyễn An',
  classId: 'c1',
  className: 'IELTS 6.5',
  walletBalance: 50_000,
};

export const secondReceipt: IncomeTransactionDetail = {
  ...incomeRow,
  id: 'r2',
  receiptNo: 'PT-260730-004',
};

export const incomeResponse: CenterReportIncomeDetailsResponse = {
  success: true,
  month: '2026-07',
  type: 'income',
  period: { startDate: '2026-07-01', endDate: '2026-07-31' },
  totalCount: 1,
  totalAmount: 1_000_000,
  rows: [incomeRow],
  nextCursor: null,
};

export const expenseResponse: CenterReportExpenseDetailsResponse = {
  success: true,
  month: '2026-07',
  type: 'expense',
  period: { startDate: '2026-07-01', endDate: '2026-07-31' },
  totalCount: 1,
  totalAmount: 200_000,
  rows: [expenseRow],
  nextCursor: null,
};
