import type { StudentIdentityArchitectureAllowlistEntry } from './student-identity-architecture.js';

/**
 * The exceptions, and the reason each one exists.
 *
 * Every entry is a path, a TypeScript node kind, and a normalized AST
 * fingerprint. Editing the code changes the fingerprint and the exception
 * stops applying, which is deliberate: an exception that survives an edit is
 * an exception nobody looked at twice. Entries are generated by running the
 * check and copying the reported fingerprint, never by hand-editing a line
 * number.
 *
 * Four reasons are legitimate and no others are:
 *
 * - `compatibility_projection_writer` — writes `classId`/`teacherId`/
 *   `enrollmentStatus` alongside the canonical enrollment, because the UI, the
 *   DocumentStore rules, and every report still read them. Removed by retirement.
 * - `legacy_compare` — the shadow-mode path that deliberately preserves the
 *   old answer so the two can be compared.
 * - `anomaly_report` — reads a legacy shape in order to *find* the problem
 *   rather than to serve from it.
 * - `reviewed_migration` — a Workstream C or D entry point a human approved.
 *
 * The post-retirement policy ignores this list entirely for legacy reads,
 * writes, and fallbacks: an exception there would describe code reading
 * something no longer written.
 */
export const STUDENT_IDENTITY_ARCHITECTURE_ALLOWLIST: StudentIdentityArchitectureAllowlistEntry[] =
  [
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION — the audit reads the old script's
  // pointer because those fifty-eight records are a candidate class of their
  // own. Recognising them is how they get an alias; the resolver branch this
  // rule exists to retire is a serving path, and this is not one.
  {
    policy: 'pre-cutover',
    path: 'scripts/normalize-student-profiles.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'reviewed_migration',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/attendance/route.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '334aa3ac324aaa3c085099199bd7a997fc97ce6a6b5346b2dee5d1ae218d325e',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/attendance/route.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '3fb780d7ff9a8b85e60053ca85d5ecbeffca7150031352b06ef4078b2fd831e3',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/attendance/route.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '46ff1e15ef7df3d2735091c64cce775011fa3198e6e515a5bc25782c4eb78c5e',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/attendance/route.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '88237e84f8ab9c01d61352dc5de657660c10d2843ffda4a4c105e299a2778cf6',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'scripts/backfill-promoted-missing-sessions.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'fc04a2a04fb806b67f7a965b26c80480e70acfd34ae66c6a8487440d7d5fe63d',
    reason: 'reviewed_migration',
  },
  // AUTHORITATIVE_PROFILE_CLASS_QUERY
  {
    policy: 'pre-cutover',
    path: 'scripts/create-office-academic-zalo-snapshot.ts',
    nodeKind: 'CallExpression',
    astFingerprint: '9587db65f8aa1e897fd3548631ea422b0aad1a28227882801f60bda9f97fd7af',
    reason: 'reviewed_migration',
  },
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION
  {
    policy: 'pre-cutover',
    path: 'scripts/merge-duplicate-student-records.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'reviewed_migration',
  },
  // AUTHORITATIVE_PROFILE_CLASS_QUERY
  {
    policy: 'pre-cutover',
    path: 'scripts/migrate-course-closing-state.ts',
    nodeKind: 'CallExpression',
    astFingerprint: '9587db65f8aa1e897fd3548631ea422b0aad1a28227882801f60bda9f97fd7af',
    reason: 'reviewed_migration',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'scripts/migrate-tuition-records.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'a2b54058d92f3f86bc2b042eadfb701ad1312af1c99f1945209a9b5177e73e90',
    reason: 'reviewed_migration',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'scripts/migrate-tuition-records.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'c944885e6e3d8869b733b4c02678bb22e421fa83cc2cb4627b4c84aa2ce0e8e5',
    reason: 'reviewed_migration',
  },
  // AUTHORITATIVE_PROFILE_CLASS_QUERY
  {
    policy: 'pre-cutover',
    path: 'scripts/resend-office-academic-zalo.ts',
    nodeKind: 'CallExpression',
    astFingerprint: '9587db65f8aa1e897fd3548631ea422b0aad1a28227882801f60bda9f97fd7af',
    reason: 'reviewed_migration',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'scripts/resend-office-academic-zalo.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '1b0633af507ccf62dd35d8ba90edd2c807aebbb1f183367221c1ba61b6871d8d',
    reason: 'reviewed_migration',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'scripts/resend-office-academic-zalo.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '5a39ea011bd0d951d1008a3de71237570d7f2087b103258402b9d6d48fff31b7',
    reason: 'reviewed_migration',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'scripts/resend-office-academic-zalo.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '20fb7bca2883badbaec96f4eefab4f76af9e2845b34d01cea02740d110dc40f1',
    reason: 'reviewed_migration',
  },
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION
  {
    policy: 'pre-cutover',
    path: 'scripts/student-profile-normalization/admissionSearchBackfill.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'reviewed_migration',
  },
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION
  {
    policy: 'pre-cutover',
    path: 'scripts/student-profile-normalization/census.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'reviewed_migration',
  },
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION
  {
    policy: 'pre-cutover',
    path: 'scripts/student-profile-normalization/planner.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'reviewed_migration',
  },
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION
  {
    policy: 'pre-cutover',
    path: 'scripts/student-profile-normalization/rehearsalFixture.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'reviewed_migration',
  },
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION
  {
    policy: 'pre-cutover',
    path: 'scripts/student-profile-normalization/verifier.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'reviewed_migration',
  },
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION
  {
    policy: 'pre-cutover',
    path: 'scripts/student-profile-retirement/planner.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'reviewed_migration',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/auth/handlers/passwordManagement.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '35dc575574e5a3b9fe5de4aa2163a6052b23ba1cad760b5de5ee945a21740ad3',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/auth/handlers/passwordManagement.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '00a98ac2e4d39387162fa8342b529cf9a6c81d464ac3402f3f28d3a1d3c93b37',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/auth/handlers/passwordManagement.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '8787765a0d0a0bf02a55dc80c2c18f58a9c3c4c5d9d17d977f7170764ac655ee',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/auth/handlers/staffAccountManagement.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'ee7d77bcca386e068db1bc59f2eb1112f3ecbe883f386d7c106896d0c2d502cb',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/auth/handlers/studentAuth.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'e4903bfabe25fdb896ab4ba3a0482ea11784d2ebed50e5198349013ddbeed491',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/classes/handlers/classAvailabilityHandlers.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '723e9e5224a591cdf193987051366ba0e3ed02fd5c2ac3d4971737f9365b6d5b',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/classes/handlers/classAvailabilityHandlers.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '1d2d42d2969a3b2bd60976da480f858b1a6575db73099e59a3077c7b70b1f94a',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/classes/handlers/classAvailabilityHandlers.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '1aa8b6ac6a48c3787845fe309ea3a45ee75bb57a5f984a460ad6086ff140e84c',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/classes/handlers/classSubstituteHandlers.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '460fbb38aaea4033ca9e98e137fff68756288d6eca0800c6f106bb24625126ef',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/classes/handlers/classSubstituteHandlers.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '296e54fb7c196aa9f7190a61c01923bda62a90899248a9d5360d84bc52c3f3a8',
    reason: 'compatibility_projection_writer',
  },
  // AUTHORITATIVE_PROFILE_CLASS_QUERY
  {
    policy: 'pre-cutover',
    path: 'server/api/classes/helpers/classHelpers.ts',
    nodeKind: 'CallExpression',
    astFingerprint: 'bb0eac09a8fad19cf9701e9146e7cadeebba480f32e925451f4be878896c72a7',
    reason: 'legacy_compare',
  },
  // AUTHORITATIVE_PROFILE_CLASS_QUERY
  {
    policy: 'pre-cutover',
    path: 'server/api/classes/helpers/courseClosing.ts',
    nodeKind: 'CallExpression',
    astFingerprint: '9587db65f8aa1e897fd3548631ea422b0aad1a28227882801f60bda9f97fd7af',
    reason: 'legacy_compare',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/edu/handlers/assignments.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'af079836eae38cf670ae4101a7ab8d797df8fdc4e49601f33916420c9103d57c',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/edu/handlers/evaluations.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'ad58ca3a97c94c3dabec1a5906a829dce639abfe8ce4fd6461c031da571ec77d',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/finance/handlers/manualReceiptWallet.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '2587913b84307373341c97bd544a9b05608bc80955a23a015ec2de333240081d',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/finance/handlers/wallet.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '3f31fa8b281e512cb4ab2c7ac0d824650c13d5ab9f252b9beecd891fb93a39a2',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/accounting/courseLedgerWriter.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '4c912e501358b3af1c8397cd5b1c08c02112e532bd7d417f09afb1f827177015',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/payments/tuitionPayments.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'e31e86c64648b07e013f742b4d7b211e73b3bff905bd0cfce33f0c4b8a220953',
    reason: 'compatibility_projection_writer',
  },
  // AUTHORITATIVE_PRESENTATION_DEDUPE — inside the explicit
  // `control.mode === 'legacy_compare'` branch, which is the one mode whose
  // whole purpose is to return the legacy answer unchanged.
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/services/dashboardAggregateService.ts',
    nodeKind: 'Identifier',
    astFingerprint: 'f4519fccf5675f5f76eb93db6b2f6b11fc3620673733c5f8dc4017579db44f19',
    reason: 'legacy_compare',
  },
  // AUTHORITATIVE_PRESENTATION_DEDUPE — inside the explicit
  // `control.mode === 'legacy_compare'` branch, which is the one mode whose
  // whole purpose is to return the legacy answer unchanged.
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/services/dashboardAggregateService.ts',
    nodeKind: 'Identifier',
    astFingerprint: 'd0065de0f3a64edd3bd4bcd48c1be67db53f8ef4d74af564fe3b6d823c177892',
    reason: 'legacy_compare',
  },
  // ANONYMOUS_STUDENT_DOCUMENT_CREATE
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/student/studentCreation.ts',
    nodeKind: 'CallExpression',
    astFingerprint: 'cdba386e00e3af8d8d0b0167da14c04bee02db1b2ab350fb9f0f65f0f3f8e953',
    reason: 'legacy_compare',
  },
  // AUTHORITATIVE_PROFILE_CLASS_QUERY
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/student/studentCreation.ts',
    nodeKind: 'CallExpression',
    astFingerprint: '9587db65f8aa1e897fd3548631ea422b0aad1a28227882801f60bda9f97fd7af',
    reason: 'legacy_compare',
  },
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/student/studentIdentityHealthService.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'anomaly_report',
  },
  // LEGACY_CODE_FALLBACK
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/student/studentIdentityResolver.ts',
    nodeKind: 'Identifier',
    astFingerprint: '0ff41ba7c3175927a82c4ef249f819e394f6416584408d61e2aa233c2428b323',
    reason: 'legacy_compare',
  },
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/student/studentIdentityResolver.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/student/studentProgression.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '2e5654c19a319710652ae9b7e41eaac8f742b05e83dbb475c48562e5a181cb4b',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/payments/payos/handlers/create.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '9fb4b15a700109bab215f5c8a13299c285b30ce80fd2636f0764362d18a02a04',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/payments/payos/handlers/create.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'd2c9fddeced5e53117c5ea9b85583b4b045705d1eaf09c498966fc59a610feea',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/payments/payos/handlers/shared.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'ba83f38525a3b1244572f67a4b36820c1e6eb5dfcb0fc7c679d82c4caca82ff2',
    reason: 'compatibility_projection_writer',
  },
  // AUTHORITATIVE_PROFILE_CLASS_QUERY
  {
    policy: 'pre-cutover',
    path: 'server/api/read/handlers/readers.ts',
    nodeKind: 'CallExpression',
    astFingerprint: '9587db65f8aa1e897fd3548631ea422b0aad1a28227882801f60bda9f97fd7af',
    reason: 'legacy_compare',
  },
  // AUTHORITATIVE_PROFILE_CLASS_QUERY
  {
    policy: 'pre-cutover',
    path: 'server/api/read/handlers/readers.ts',
    nodeKind: 'CallExpression',
    astFingerprint: '3631745a2a6dd3088a1fd5fad1d6eac2a30d761815c1b3b39c99613c81917bd9',
    reason: 'legacy_compare',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/zalo/handlers/bulkNotificationJobs.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'c963027539b6d866bf910b67194664e36130e648b6dd4639e7e90aed94765263',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/zalo/handlers/bulkNotificationJobs.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'f5a7e9b6c94efe34325a4399fc8fa4f7ac92891ee5ed4d0a4628b5ec6522691d',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_SOFT_MERGE_POINTER_RESOLUTION
  {
    policy: 'pre-cutover',
    path: 'shared/studentIdentity.ts',
    nodeKind: 'Identifier',
    astFingerprint: '79788937b8df2541aa9e18ac987db14cd86430ad1af7ee7f9ce9e7249d3591e9',
    reason: 'compatibility_projection_writer',
  },
  // AUTHORITATIVE_PRESENTATION_DEDUPE
  {
    policy: 'pre-cutover',
    path: 'shared/studentRecords.ts',
    nodeKind: 'Identifier',
    astFingerprint: 'e27e2c4882c6df80aabe5c028008928d167bc9eeec6e2fb72fd3cfad2c253d20',
    reason: 'anomaly_report',
  },
  // AUTHORITATIVE_PRESENTATION_DEDUPE
  {
    policy: 'pre-cutover',
    path: 'shared/studentRecords.ts',
    nodeKind: 'Identifier',
    astFingerprint: 'f4519fccf5675f5f76eb93db6b2f6b11fc3620673733c5f8dc4017579db44f19',
    reason: 'anomaly_report',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'src/lib/availability/teacherBusyNotes.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'ca177f95b6768b3934756f1a23255b626019b49efb5cc6e9624368a4f83da31d',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'src/pages/accounting/components/GenerateLedgersDialog.tsx',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'a2964e44d714afa47ff853b84ad6f277295fe19d138f69b9886f04f374bf0a0b',
    reason: 'compatibility_projection_writer',
  },
  



  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/attendance/route.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'f313e5dd585440970d0fc3e24cc7f4b27f489a01add86094625290e473912085',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE â€” toggle restore payload still projects
  // class and teacher until the compatibility fields are retired.
  {
    policy: 'pre-cutover',
    path: 'server/api/attendance/route.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '1f7336b9c59d958df5aafaf293b531f7e220781379ea48250abc10812207ebfc',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE â€” cycle restore payload has the same
  // reviewed compatibility projection.
  {
    policy: 'pre-cutover',
    path: 'server/api/attendance/route.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'f8625cdc02a8b44d9928ff5babae8974b336dd50c08cecbfdec73f49eb3a5e78',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE â€” bulk restore payload has the same
  // reviewed compatibility projection.
  {
    policy: 'pre-cutover',
    path: 'server/api/attendance/route.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'dba72db8bb91000955c5917c402d87807ceb3a6a8306b35e38f10e6b4bd17f04',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/admissions/handlers/createTrial.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'e204b488c61b02a0435432d5c62851faaddb071443adadfdc5634b7172f648b6',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/classes/records/courseClosingRecordRepository.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'f0eba2722737dfcc32bf6b9735160a98188936237aa564abf7fdfdd035f96abf',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/edu/handlers/assignmentAttemptDrafts.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '864f6c90badb18a71813187105a6392d58ef6282d9bbc5ff29b362435251b42c',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/edu/handlers/assignments.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '8048b0b21cec080b7ed2792cec9d9a657c7bc129ac7555f9436bce5f7e153446',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/edu/handlers/assignments.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '8e844988ae588bd41497337ad9cbcaf96559954fe1c2c015589d1b7e927d38a8',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/edu/handlers/evaluations.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '45b5f9902069c55b56d97e040b1090fb2dcd8aebd00fe23cde2e6f4ec6be4f9c',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/finance/handlers/manualReceiptWallet.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '635eb865d887b38711bcc3526d1338422eaaa08c440e35284ea4a7f48a5bd355',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/finance/handlers/receipts.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '640b0f0ba799252441a711921c8b6d1a222795b2dbb0fb8343b5079442ec34cc',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/knowledge-bank/handlers/printRequests.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '2e0afb5193ed16083bac36c1206c8e084e90e696a84c027dd647b582ea14dd6b',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/services/invoiceService.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'c15e836e83fdb3ca5df3c96b3499ea2885be795654264172f1fe7de41d032186',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'server/api/zalo/handlers/messagesHandler.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '36974c989c1383f2a213b49bb480241cd110b97744095b061331fa94eb9e2c60',
    reason: 'compatibility_projection_writer',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'scripts/allocate-mai-ly-wallet-remainder.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '1f63cc6deb659a9eafea79c2e72e1644c3390e33877155cceaf49eb4c0552d34',
    reason: 'reviewed_migration',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'scripts/rebuild-open-course-ledgers.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'b9d1cefba52b13591a13d9af79347c0d907b3758aa15e4c810aeb0cd98a965c4',
    reason: 'reviewed_migration',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  {
    policy: 'pre-cutover',
    path: 'scripts/rebuild-open-course-ledgers.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: 'a24894a2b3d4d0010f6d01ab2de04d15473fad988fc85bc65703a280d9063065',
    reason: 'reviewed_migration',
  },
  // LEGACY_PROJECTION_FIELD_WRITE
  // AUTHORITATIVE_PROFILE_CLASS_QUERY
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/student/courseTermRoster.ts',
    nodeKind: 'CallExpression',
    astFingerprint: '8fd5f411a53305b2fc1d5a4781dbcd7b1d2e2463fb96ce938a34331a3ac22431',
    reason: 'legacy_compare',
  },
  // LEGACY_PROJECTION_FIELD_WRITE — this is a reviewed class-level tuition
  // summary projection, not a write to a student identity profile.
  {
    policy: 'pre-cutover',
    path: 'server/api/lib/services/adminClassTuitionSnapshotService.ts',
    nodeKind: 'ObjectLiteralExpression',
    astFingerprint: '9b6fe6930f212c97c9294bf1b0c19228021e80593441b02f6dbee59f7f27fbb1',
    reason: 'compatibility_projection_writer',
  },
  ];
